# Generated by Django 4.2.6 on 2023-10-23 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_creator',
            new_name='profile_creator',
        ),
    ]
