# Generated by Django 4.2.6 on 2023-10-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_user_creator_post_profile_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_creator_comment',
            new_name='profile_comment_creator',
        ),
    ]
